from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import MonetaryPenaltyViewSet

# Create a router for your viewset
router = DefaultRouter()
router.register(r'monetary-penalties', MonetaryPenaltyViewSet)

urlpatterns = [
    # Include the URLs generated by the router
    path('', include(router.urls)),
]
