# Generated by Django 4.2.5 on 2023-09-16 09:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonetaryPenalty',
            fields=[
                ('monetary_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_id', models.CharField(blank=True, max_length=255, null=True)),
                ('premiseId', models.CharField(blank=True, max_length=255, null=True)),
                ('startDate', models.CharField(blank=True, max_length=255, null=True)),
                ('endDate', models.CharField(blank=True, max_length=255, null=True)),
                ('penaltyAuthority', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'MonetaryPenalty',
            },
        ),
    ]
